cpu_usage_indicator: cpu_usage_indicator.go led.go proc_stat.go Makefile
	go build cpu_usage_indicator.go led.go proc_stat.go

clean:
	rm -rf cpu_usage_indicator

run: cpu_usage_indicator
	sudo ./cpu_usage_indicator

